### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Henry-zhangs** [mazurowski-lab/SegmentAnyBone#10]
thanks for your team’s job. Could you tell me how to train on my datasets？

**Comment by Guhanxue** [comment]
Hi, based on our previous study, the method to fine-tune SAM and which strategy is the best one pretty various between datasets. If you would like to finetune SAM by yourself on public dataset, do you mind referring to my other repo: https://github.com/mazurowski-lab/finetune-SAM. We provided a step-by-step tuturiol about how to fine-tune SAM to custom medical imaging dataset. If you are interested in fine-tune our SegmentAnyBone model on your dataset; we are preparing this now and we will update that in a week.
