### ISSUE TITLE
Lack of Clear documentation 

### ISSUE THREAD

**Issue by ZeeshanGeoPk** [mazurowski-lab/SegmentAnyBone#12]
Hi there!
I appreciate your work but the repo lacks the proper doc. A beginner programmer should be able to use it easily.

There are no sample input and output images. 
One should be able to see sample results in doc/readMe.

You should add some sample images and their results.

I hope, it doesn't offend you.

Thanks and regards,
Muhammad Zeeshan

**Comment by jamesobutler** [comment]
Cc @Zaferyildiz on whether improvements to documentation could be made to support this user?

**Comment by Zaferyildiz** [comment]
@ZeeshanGeoPk @jamesobutler Sample data and output is provided under /[images](https://github.com/mazurowski-lab/SegmentAnyBone/tree/main/images) and /[predicted_masks](https://github.com/mazurowski-lab/SegmentAnyBone/tree/main/predicted_masks) folders. You can find an example screenshot in the readme file as well.
