### ISSUE TITLE
extention to CT imaging

### ISSUE THREAD

**Issue by Aakanksha-Rana** [mazurowski-lab/SegmentAnyBone#13]
Is there any plan to test it on CT data as well ? It would be very useful as in some cases MRIs arent available and CT are mostly used for e.g only abdomen cases

**Comment by AkashKarnatak** [comment]
Both MRI and CT-scan uses dicom format, so I don't think you would have any problem using this model for CT-scan. Btw what use case are you working on?

**Comment by jamesobutler** [comment]
Cc @Zaferyildiz about @AkashKarnatak statement about using this model CT scans.

**Comment by Zaferyildiz** [comment]
@Aakanksha-Rana @AkashKarnatak @jamesobutler SegmentAnyBone is particularly trained and tested on only MRI data.
