### ISSUE TITLE
Problem with requirements.txt

### ISSUE THREAD

**Issue by ReiniertB** [mazurowski-lab/SegmentAnyBone#4]
Hi, your code seems great but I have a hard time installing the environment with the requirements.txt file.
I built a conda environment with python 3.9 but when I try to run pip install -r requirements.txt I get the following error:

ERROR: Ignored the following yanked versions: 0.0.post2
ERROR: Ignored the following versions that require a different python version: 2.5.2 Requires-Python !=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9dev,>=2.7
ERROR: Could not find a version that satisfies the requirement sklearn==1.3.2 (from versions: 0.0, 0.0.post1, 0.0.post4, 0.0.post5, 0.0.post7, 0.0.post9, 0.0.post10, 0.0.post11, 0.0.post12)
ERROR: No matching distribution found for sklearn==1.3.2

Other python versions do not seem to make a difference.
Is there a mistake in your requirements file or should I use a different python version?

Thanks in advance!

**Comment by Zaferyildiz** [comment]
requirements.txt is updated. Could you please try it again? I have tried it with conda by using python 3.8, and it seems the problem is solved now. Feel free to open the issue again if the problem is not solved on your side. Thank you for your interest!
