### ISSUE TITLE
Unexpected keys while loading state_dict for Sam.

### ISSUE THREAD

**Issue by mareksocha** [mazurowski-lab/SegmentAnyBone#6]
I get the following error when I try to load state_dict from file 'bone_sam.pth' according to instructions in the jupyter notebook. I have tried to run it on both Python 3.8 and Python 3.10. I also tried different "vit_*" versions, but they did not work either. 

Traceback (most recent call last):
  File "bone_segmentation.py", line 107, in <module>
    sam_fine_tune.load_state_dict(torch.load(os.path.join(checkpoint_directory, 'bone_sam.pth'),
  File "env\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sam:
	Unexpected key(s) in state_dict: "image_encoder.layers.1.blocks.0.MLP_Adapter.D_fc1.weight", "image_encoder.layers.1.blocks.0.MLP_Adapter.D_fc1.bias", "image_encoder.layers.1.blocks.0.MLP_Adapter.D_fc2.weight", "image_encoder.layers.1.blocks.0.MLP_Adapter.D_fc2.bias", "image_encoder.layers.1.blocks.0.Space_Adapter.D_fc1.weight", "image_encoder.layers.1.blocks.0.Space_Adapter.D_fc1.bias", "image_encoder.layers.1.blocks.0.Space_Adapter.D_fc2.weight", "image_encoder.layers.1.blocks.0.Space_Adapter.D_fc2.bias", "image_encoder.layers.1.blocks.1.MLP_Adapter.D_fc1.weight", "image_encoder.layers.1.blocks.1.MLP_Adapter.D_fc1.bias", "image_encoder.layers.1.blocks.1.MLP_Adapter.D_fc2.weight", "image_encoder.layers.1.blocks.1.MLP_Adapter.D_fc2.bias", "image_encoder.layers.1.blocks.1.Space_Adapter.D_fc1.weight", "image_encoder.layers.1.blocks.1.Space_Adapter.D_fc1.bias", "image_encoder.layers.1.blocks.1.Space_Adapter.D_fc2.weight", "image_encoder.layers.1.blocks.1.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.0.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.0.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.0.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.0.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.0.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.0.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.0.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.0.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.1.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.1.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.1.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.1.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.1.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.1.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.1.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.1.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.2.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.2.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.2.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.2.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.2.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.2.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.2.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.2.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.3.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.3.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.3.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.3.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.3.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.3.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.3.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.3.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.4.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.4.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.4.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.4.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.4.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.4.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.4.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.4.Space_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.5.MLP_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.5.MLP_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.5.MLP_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.5.MLP_Adapter.D_fc2.bias", "image_encoder.layers.2.blocks.5.Space_Adapter.D_fc1.weight", "image_encoder.layers.2.blocks.5.Space_Adapter.D_fc1.bias", "image_encoder.layers.2.blocks.5.Space_Adapter.D_fc2.weight", "image_encoder.layers.2.blocks.5.Space_Adapter.D_fc2.bias", "mask_decoder.transformer.layers.0.MLP_Adapter.D_fc1.weight", "mask_decoder.transformer.layers.0.MLP_Adapter.D_fc1.bias", "mask_decoder.transformer.layers.0.MLP_Adapter.D_fc2.weight", "mask_decoder.transformer.layers.0.MLP_Adapter.D_fc2.bias", "mask_decoder.transformer.layers.0.Adapter.D_fc1.weight", "mask_decoder.transformer.layers.0.Adapter.D_fc1.bias", "mask_decoder.transformer.layers.0.Adapter.D_fc2.weight", "mask_decoder.transformer.layers.0.Adapter.D_fc2.bias", "mask_decoder.transformer.layers.1.MLP_Adapter.D_fc1.weight", "mask_decoder.transformer.layers.1.MLP_Adapter.D_fc1.bias", "mask_decoder.transformer.layers.1.MLP_Adapter.D_fc2.weight", "mask_decoder.transformer.layers.1.MLP_Adapter.D_fc2.bias", "mask_decoder.transformer.layers.1.Adapter.D_fc1.weight", "mask_decoder.transformer.layers.1.Adapter.D_fc1.bias", "mask_decoder.transformer.layers.1.Adapter.D_fc2.weight", "mask_decoder.transformer.layers.1.Adapter.D_fc2.bias".

**Comment by Guhanxue** [comment]
Hi, it seems like you don't add Adapter Blocks to your network structure. Did you add these two arguments to your codes? args.if_mask_decoder_adapter=True
args.if_encoder_adapter = True

**Comment by mareksocha** [comment]
Hello,
Thank you, adding mentioned arguments fixed my issue.
